"""First migration

Revision ID: 382ea58de0a8
Revises: 
Create Date: 2020-12-31 10:00:01.637557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382ea58de0a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferd.py',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transferd.py')
    # ### end Alembic commands ###
